apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jenkins-apache-project
  name: jenkins-apache-project
spec:
  ports:
  - port: 3002
    protocol: TCP
    targetPort: 3002
  selector:
    app: jenkins-apache-project
status:
  loadBalancer: {}