apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jenkins-apache-site
  name: jenkins-apache-site
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: jenkins-apache-site
  type: NodePort
status:
  loadBalancer: {}
